require("core.options")
require("core.keymaps")
require("plugin")
require("plugin.lsp")
require("plugin.web_devicons")
-- require("plugin.colorscheme")
-- require("plugin.telescope")
-- require("plugin.terminal")
require("plugin.autocmd")
-- vim.opt.rtp:prepend("~/Repo/neovim-temp-file")
-- require("neovim-temp-file")
